language: common-lisp
sudo: false # lets try new infrastructure

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_BRANCH=release
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - COVERAGE_EXCLUDE=t
  matrix:
    - LISP=sbcl-bin COVERALLS=true

install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh
  - ros install prove

#  cache:
#    directories:
#      - $HOME/.roswell
#      - $HOME/.config/common-lisp

script:
  - run-prove cl-amqp.test.asd